export { default as VMap } from '@/components/maptalks/v-map.vue'
export { default as VPubLayer } from './pub-layer/index.jsx'
export { default as VTiandituLayer } from './tianditu/index.jsx'
export { default as VVectorLayer } from '@/components/maptalks/v-vector-layer.vue'
export { default as VMarker } from '@/components/maptalks/geometry/v-marker.js'
export { default as VLine } from '@/components/maptalks/geometry/v-line.js'
export { default as VPolygon } from '@/components/maptalks/geometry/v-polygon.js'
